name: Auto-approve khajavi's PRs

on: pull_request_target

jobs:
  auto-approve-renovate-prs:
    runs-on: ubuntu-latest
    steps:
      - run: git fetch --all
      - name: Approve PR
        run: gh pr review --approve ${{ github.event.number }}
        if: github.actor == 'khajavi'
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
