name: CI
env:
  owner: foo
  repo: GithubActionWebhookExample
on:
  release:
    types:
      - published
  workflow_dispatch: {}
  repository_dispatch:
    types: [update-docs]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered"
      - name: Print Event Object
        run: echo '${{ toJson(github) }}'
      - name: Git Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          package_name="${{ github.event.client_payload.package_name }}"
          package_version="${{ github.event.client_payload.package_version }}"
          echo "$package_name@$package_version\n" >> README.md
          git add README.md
          commit_message="Update $package_name to $package_version"
          git commit -m "$commit_message" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          token: ${{ secrets.MY_PAT }}
          body: |-
            Autogenerated changes after running the `sbt docs/generateReadme` command of the [zio-sbt-website](https://zio.dev/zio-sbt) plugin.
            
            I will automatically update the README.md file whenever there is new change for README.md, e.g.
              - After each release, I will update the version in the installation section.
              - After any changes to the "docs/index.md" file, I will update the README.md file accordingly.
          branch: zio-sbt/update-readme
          commit-message: Update README.md
          delete-branch: true
          title: Update README.md
