name: CI
env:
  owner: foo
  repo: GithubActionWebhookExample
on:
  release:
    - published
  repository_dispatch:
    types: [update-docs]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered"
      - name: Print Event Object
        run: echo '${{ toJson(github) }}'